import { useState } from 'react'
import { AlertTriangle, Ban, CheckCircle2, Database, FileCheck2, HeartPulse, Link as LinkIcon, LockKeyhole, RefreshCw, Search, ShieldCheck, Sparkles, UserPlus } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useDemo } from './DemoState'

function PageTitle({ eyebrow, title, detail, action }: { eyebrow: string; title: string; detail: string; action?: React.ReactNode }) {
  return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{detail}</p></div>{action}</div>
}
function Pill({ children, tone = 'neutral' }: { children: React.ReactNode; tone?: string }) { return <span className={`pill pill-${tone}`}>{children}</span> }
function ActionButton({ children, onClick }: { children: React.ReactNode; onClick: () => void }) { return <button className="btn btn-secondary" onClick={onClick}>{children}</button> }

export function ResourcePage() {
  const { foodKitsAvailable, medicineUnitsAvailable, ambulancesAvailable, hospitalBedsAvailable, operationalDecision } = useDemo()
  const resources = [['Food kits', String(foodKitsAvailable), 'Available'], ['Medicine units', String(medicineUnitsAvailable), 'Review stock'], ['Ambulances', String(ambulancesAvailable), 'Available'], ['Hospital beds', String(hospitalBedsAvailable), 'Available']]
  const [refreshed, setRefreshed] = useState(false)
  return <div className="page-content"><PageTitle eyebrow="RESOURCE INVENTORY" title="Resource inventory" detail="Track available relief units, medicine capacity, vehicles, and budget before an allocation is approved." action={<ActionButton onClick={() => setRefreshed(true)}><RefreshCw size={15} />Refresh inventory</ActionButton>} />{refreshed && <div className="notice-bar"><CheckCircle2 size={15} />Inventory refreshed from the seeded operational context.</div>}<div className="resource-grid">{resources.map(([name, value, status]) => <div className="panel resource-card" key={name}><div className="kpi-top"><span>{name}</span><Database size={15} /></div><strong>{value}</strong><Pill tone={status === 'Review stock' ? 'warn' : 'good'}>{status}</Pill><span className="resource-note">Last checked 09:42 · demonstration data</span></div>)}</div><div className="panel"><div className="inventory-state-note"><strong>Gross inventory: 500 food kits</strong><span>Approved commitments: {operationalDecision.inventory.approvedCommitments} · Operationally available: {operationalDecision.inventory.currentStock} · Pending allocation: {operationalDecision.inventory.pendingAllocation} · Projected balance after approval: {operationalDecision.inventory.afterPendingAllocation} · Approval status: {operationalDecision.allocation.status === 'pending' ? 'Pending coordinator approval' : operationalDecision.allocation.status}</span></div><div className="section-title"><div><div className="eyebrow">CONSTRAINTS</div><h2>Allocation checks</h2><p>The Resource Allocation Rules checks inventory, capacity, route access, budget, expiry, and duplicate categories before creating an approval request.</p></div></div><div className="feature-strip"><div><CheckCircle2 size={16} /><strong>{operationalDecision.inventory.currentStock} food kits</strong><span>Operationally available · {operationalDecision.inventory.pendingAllocation} pending</span></div><div><HeartPulse size={16} /><strong>{medicineUnitsAvailable} medicine units</strong><span>Separate medical inventory</span></div><div><Database size={16} /><strong>{hospitalBedsAvailable} hospital beds</strong><span>District General Hospital capacity</span></div><div><Ban size={16} /><strong>Coastal Link blocked</strong><span>Ring Road alternative available</span></div></div></div></div>
}

export function BeneficiaryPage() {
  const { beneficiaries } = useDemo(); const [query, setQuery] = useState(''); const filtered = beneficiaries.filter((item) => `${item.reference} ${item.location}`.toLowerCase().includes(query.toLowerCase()))
  return <div className="page-content"><PageTitle eyebrow="BENEFICIARY REGISTRY" title="Beneficiary registry" detail="Search authorized references and vulnerability signals without exposing unnecessary personal data." action={<Link to="/field" className="btn btn-primary"><UserPlus size={15} />Register offline</Link>} /><div className="panel"><div className="panel-head"><div><div className="eyebrow">AUTHORIZED RECORDS</div><h3>{filtered.length} visible records</h3></div><input className="compact-search" aria-label="Search beneficiaries" placeholder="Search reference or camp" value={query} onChange={(event) => setQuery(event.target.value)} /></div><div className="beneficiary-table"><div className="table-head"><span>Reference</span><span>Location</span><span>Household</span><span>Need</span><span>Status</span></div>{filtered.map((item) => <div className="table-row" key={item.id}><strong className="mono">{item.reference}</strong><span>{item.location}</span><span>{item.householdSize} people</span><Pill tone={item.urgency === 'Critical' ? 'danger' : 'warn'}>{item.urgency} · {item.vulnerability}</Pill><Pill tone={item.verified ? 'good' : 'warn'}>{item.verified ? 'Verified' : 'Local only'}</Pill></div>)}</div>{filtered.length === 0 && <div className="empty-state"><Search size={20} /><strong>No matching beneficiaries</strong><span>Try a reference or camp name.</span></div>}</div></div>
}

export function ReportsPage() {
  const { agentRuns, runTriage } = useDemo(); const [report, setReport] = useState('Floodwater is rising near Coastal Link. Camp Beta needs food kits and medicine; bridge access is uncertain.'); const triage = agentRuns.find((run) => run.agent === 'Incident Triage Rules')
  return <div className="page-content"><PageTitle eyebrow="FIELD REPORTS" title="Field-report queue" detail="Unstructured reports stay marked unverified until an authorized person confirms them." action={<ActionButton onClick={runTriage}><Sparkles size={15} />Run triage rules</ActionButton>} /><div className="report-workspace"><div className="panel form-panel"><div className="panel-head"><div><div className="eyebrow">NEW REPORT · UNVERIFIED</div><h3>Submit field signal</h3></div><Pill tone="warn">Human confirmation</Pill></div><label>Report narrative<textarea value={report} onChange={(event) => setReport(event.target.value)} /></label><ActionButton onClick={runTriage}><FileCheck2 size={15} />Queue for triage</ActionButton><div className="privacy-callout"><AlertTriangle size={15} /><span>Report content is evidence, not a final decision. Location and urgency remain uncertain until review.</span></div></div><div className="panel"><div className="panel-head"><div><div className="eyebrow">TRIAGE RESULT</div><h3>{triage ? 'Incident Triage Rules output' : 'Awaiting analysis'}</h3></div>{triage && <Pill tone="good">Deterministic rules</Pill>}</div>{triage ? <><div className="agent-summary"><strong>{triage.summary}</strong><span>{triage.uncertainty}</span></div><div className="confidence"><span className="confidence-label">Confidence</span><span className="confidence-value">{Math.round(triage.confidence * 100)}%</span><div className="meter"><i style={{ width: `${triage.confidence * 100}%` }} /></div></div><div className="evidence-list">{triage.evidence.map((item) => <div className="evidence-item" key={item.id}><span className="evidence-id">{item.label}</span><span>{item.detail}</span></div>)}</div></> : <div className="empty-state"><Sparkles size={20} /><strong>No report analyzed</strong><span>Queue the report to create a reviewable incident record.</span></div>}</div></div></div>
}

export function HistoryPage() {
  const { agentRuns } = useDemo(); const [selected, setSelected] = useState<string>()
  const run = agentRuns.find((item) => item.id === selected)
  return <div className="page-content"><PageTitle eyebrow="RULE ACTIVITY" title="Rule activity & trace" detail="Inspect structured outputs, evidence, uncertainty, and the human decision path." />{run && <div className="trace-drawer"><div className="trace-head"><div><div className="eyebrow">RULE TRACE · DETERMINISTIC RULES</div><h3>{run.agent}</h3><span>{run.createdAt} · {run.duration}</span></div><ActionButton onClick={() => setSelected(undefined)}>Close trace</ActionButton></div><div className="trace-grid"><div><span>OUTPUT</span><strong>{run.summary}</strong></div><div><span>STATUS</span><strong>{run.status}</strong></div><div><span>CONFIDENCE</span><strong>{Math.round(run.confidence * 100)}%</strong></div><div><span>APPROVAL</span><strong>{run.requiresApproval ? 'Required' : 'Not required'}</strong></div></div><div className="trace-section"><span className="eyebrow">EVIDENCE</span>{run.evidence.map((item) => <div className="evidence-item" key={item.id}><span className="evidence-id">{item.label}</span><span>{item.detail}</span></div>)}</div><div className="trace-section trace-warning"><AlertTriangle size={15} /><span>{run.uncertainty}</span></div></div>}<div className="panel history-list">{agentRuns.map((item) => <div className="history-row" key={item.id}><div><span className="mono">{item.createdAt}</span><strong>{item.agent}</strong><span>{item.summary}</span></div><Pill tone={item.requiresApproval ? 'warn' : 'good'}>{item.status}</Pill><ActionButton onClick={() => setSelected(item.id)}>View rule trace</ActionButton></div>)}</div></div>
}

export function SettingsPage() {
  const [approval, setApproval] = useState(true); const [privacy, setPrivacy] = useState(true); const [fallback, setFallback] = useState(true)
  const items: [string, string, boolean, (v: boolean) => void][] = [['Human approval required', 'High-risk allocations and sensitive actions pause for an authorized coordinator.', approval, setApproval], ['Beneficiary privacy filter', 'Donor views and QR payloads hide names, phone numbers, exact addresses, and medical details.', privacy, setPrivacy], ['Deterministic rules labeling', 'Unavailable providers are labeled Deterministic rules and uncertainty remains visible.', fallback, setFallback]]
  return <div className="page-content"><PageTitle eyebrow="POLICY CONFIGURATION" title="Settings & responsible automation" detail="These controls make safety rules visible to operators; they do not bypass role permissions or human approval." action={<Pill tone="good"><ShieldCheck size={13} />Policy active</Pill>} /><div className="panel settings-panel"><div className="panel-head"><div><div className="eyebrow">RESPONSIBLE AUTOMATION CONTROLS</div><h3>Operational guardrails</h3></div><LockKeyhole size={18} /></div>{items.map(([title, detail, value, setter]) => <div className="setting-row" key={title}><div><strong>{title}</strong><span>{detail}</span></div><button className={`toggle-button ${value ? 'is-on' : ''}`} onClick={() => setter(!value)} aria-pressed={value}>{value ? 'Enabled' : 'Disabled'}</button></div>)}</div><div className="feature-strip"><div><ShieldCheck size={16} /><strong>Recommendations are not decisions</strong><span>Human operators remain accountable for approvals.</span></div><div><LockKeyhole size={16} /><strong>No diagnosis or aid denial</strong><span>Rules cannot make clinical diagnoses or deny emergency aid.</span></div><div><FileCheck2 size={16} /><strong>Every action is audit logged</strong><span>Approvals and conflicts remain traceable.</span></div></div></div>
}
